### ISSUE TITLE
Allow 2+ reference layers

### ISSUE THREAD

**Issue by oevans** [pholleran/agoAdminTools#1]
Would be great to be able to make a multi-layer basemap with more than one reference layer (e.g., Imagery with Transportation and Labels).  Could you add more fields for reference layers to allow this?

**Comment by pholleran** [comment]
Owen, it is a great idea.  I may take it on later, when I have time.  Otherwise, community contributions are always welcome.

**Comment by pholleran** [comment]
closing re: https://github.com/pholleran/agoAdminTools/pull/4
