### ISSUE TITLE
Doc Enhancement: https requires https with most browsers

### ISSUE THREAD

**Issue by dannykrouk** [pholleran/agoAdminTools#2]
A nice application.  Congratulations!  

Perhaps it is more obvious to others than it was to me, but if you are accessing a portal over https, you need to use this app over https in most browsers.  

I found that IE9 was a partial exception to this in that it allowed me to login with http to your app and https to my portal.  But, then the functions themselves did not work (the ones I tried).  

So, I think some sort of documentation (or error trapping) would be useful.  I suspect documentation is a bit more practical because the browsers I tried (IE, Chrome, Firefox) had very different behaviors when you tried to access an https portal from the app when accessed via http. There are probably browser settings that influence this as well; I didn't get into that once I (re-)discovered the https alignment principle. ;-)

**Comment by pholleran** [comment]
Link updated to reflect support for GitHub pages' https support.
